 
Total_Subscribers_M = DIVIDE(SUM('youtube_data_from_python 4'[total_subscribers]), 1000000)
Total_Views_B = DIVIDE(SUM('youtube_data_from_python 4'[total_views]), 1000000000)
Total_video_ = SUM('youtube_data_from_python 4'[total_videos])
AVG_Views_Per_Videos = DIVIDE(DIVIDE(SUM('youtube_data_from_python 4'[total_views]), SUM('youtube_data_from_python 4'[total_videos]), BLANK()), 1000000)
engagement_rate = DIVIDE(SUM('youtube_data_from_python 4'[total_subscribers]), SUM('youtube_data_from_python 4'[total_videos]), BLANK())
